---
title: "joyce"
output:
  html_document:
    theme: simplex
    df_print: paged
    code_folding: "hide"
---
```{r, echo = FALSE, message=FALSE}
##loading the packages and pulling out the imdb dataset
library(tidyverse)
library(RMySQL)
library(ggplot2)
library(RColorBrewer)
db <- dbConnect(MySQL(), 
                host = "scidb.smith.edu", 
                user = "mth292", 
                password = "RememberPi", 
                dbname = "imdb")
knitr::opts_chunk$set(connection = db, max.print = 20)
```


```{r}
female <- dbGetQuery (db,
                    'select count(ci.movie_id) as total, info as genre, production_year
from cast_info ci
join movie_info m on m.movie_id = ci.movie_id ##join to filter by person_role_id
join name n on n.id = ci.person_id ##join to filter by gender
join role_type r on r.id = ci.role_id
join title t on t.id = ci.movie_id
where r.id = 3
and n.gender = "f"
and m.info_type_id = 3
and t.production_year > 2010
group by m.info
order by total desc
limit 0,5;')
```

```{r}
ggplot(female, aes(x = genre, y = total, fill = genre)) +
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Set3") +
  labs(title = "Female")
```

```{r}
male <- dbGetQuery (db,
                    'select count(ci.movie_id) as total, info as genre, production_year
from cast_info ci
join movie_info m on m.movie_id = ci.movie_id ##join to filter by person_role_id
join name n on n.id = ci.person_id ##join to filter by gender
join role_type r on r.id = ci.role_id
join title t on t.id = ci.movie_id
where r.id = 3
and n.gender = "m"
and m.info_type_id = 3
and t.production_year > 2010
group by m.info
order by total desc
limit 0,5;')
```

```{r}
ggplot(male, aes(x = genre, y = total, fill = genre)) +
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Set3") +
  labs(title = "Male")
```

```{r}
new <- dbGetQuery (db,
                    'select count(ci.movie_id) as total, info as genre, n.gender
from cast_info ci
join movie_info m on m.movie_id = ci.movie_id ##join to filter by person_role_id
join name n on n.id = ci.person_id ##join to filter by gender
join role_type r on r.id = ci.role_id
join title t on t.id = ci.movie_id
where r.id = 3
and (n.gender is not NULL)
and m.info_type_id =3
and t.production_year >2009
and t.production_year <2016
group by m.info, n.gender
order by total desc
limit 0,5;')
```

```{r}
ggplot(new, aes(fill = genre, y = total, x = n.gender)) + 
  geom_bar(position="dodge", stat="identity") +
  facet_wrap(~genre)
```
