---
title: "mp4_nm"
output: 
  html_document:
    code folding: "hide"
---

```{r}
##loading the packages and pulling out the imdb dataset
library(tidyverse)
library(RMySQL)
library(ggplot2)
library(RColorBrewer)
db <- dbConnect(MySQL(), 
                host = "scidb.smith.edu", 
                user = "mth292", 
                password = "RememberPi", 
                dbname = "imdb")
knitr::opts_chunk$set(connection = db, max.print = 20)
```


```{r}
female_producers <- dbGetQuery (db,
                    'select count(ci.movie_id) as total, info as genre, production_year
from cast_info ci
join movie_info m on m.movie_id = ci.movie_id ##join to filter by person_role_id
join name n on n.id = ci.person_id ##join to filter by gender
join role_type r on r.id = ci.role_id
join title t on t.id = ci.movie_id
where r.id = 3
and n.gender = "f"
and m.info_type_id = 3
and t.production_year > 2010
group by m.info
order by total desc
limit 0,5;')
```


```{sql connection=db}
select count(ci.movie_id) as total, info as genre, production_year
from cast_info ci
join movie_info m on m.movie_id = ci.movie_id ##join to filter by person_role_id
join name n on n.id = ci.person_id ##join to filter by gender
join role_type r on r.id = ci.role_id
join title t on t.id = ci.movie_id
where r.id = 3
and n.gender = "f"
and m.info_type_id = 3
and t.production_year > 2010
group by m.info
order by total desc
limit 0,5;
```


```{r}
ggplot(female_producers, aes(x = genre, y = total, fill = genre)) +
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Set3")
```



